FROM ancoris/puppeteer

RUN npm install -g jest-puppeteer \
    && npm install -g @babel/plugin-transform-runtime \
    && npm install -g @babel/preset-env \
    && npm install -g @babel/runtime \
    && npm install -g babel-cli \
    && npm install -g jest \